version: "3.8"

services:
  suacebot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./.env.staging:/app/.env
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
      - .:/app
    command: watchmedo auto-restart --directory=. --pattern=*.py --recursive -- python main.py
